{{- range $key, $app := .Values.apps -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}-service
spec:
  selector:
      app: {{ $key }}
  ports:
    - name: {{ $key }}
      protocol: TCP
      {{- /* All the Hiker's Book containers are exposed on 4000 */}}
      port: 4000
      targetPort: {{ $app.service.targetPort }}
{{ end }}