{{- range $key, $db := .Values.mongodb -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-{{ $key }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-{{ $key }}
  template:
    metadata:
      labels:
        app: mongodb-{{ $key }}
    spec:
      containers:
        - name: mongodb-{{ $key }}
          image: {{ $db.image }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $db.service }}-service
spec:
  selector:
    app: mongodb-{{ $key }}
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
{{ end }}
