version: '3.5'
services:
  mongo-authentication:
    image: mongo:latest
    container_name: mongo-authentication
    hostname: mongo-authentication
    restart: always
    ports:
      - 27017:27017
  mongo-graphql:
    image: mongo:latest
    container_name: mongo-graphql
    hostname: mongo-graphql
    restart: always
    ports:
      - 27018:27017
  mongo-stages:
    image: mongo:latest
    container_name: mongo-stages
    hostname: mongo-stages
    restart: always
    ports:
      - 27019:27017
  mongo-trips:
    image: mongo:latest
    container_name: mongo-trips
    hostname: mongo-trips
    restart: always
    ports:
      - 27020:27017
  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo-express
  #   hostname: mongo-express
  #   restart: always
  #   depends_on:
  #     - mongo-authentication
  #     - mongo-graphql
  #     - mongo-stages
  #     - mongo-trips
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: root
  #     ME_CONFIG_BASICAUTH_PASSWORD: password
  #     ME_CONFIG_MONGODB_SERVER: 'mongo-authentication,mongo-graphql,mongo-stages,mongo-trips'
  #   ports:
  #     - 8081:8081