version: '3.5'
services:
  hikers-book-ui-hikers-book:
    image: radoslavirha/hikers-book-ui-hikers-book:$VERSION
    container_name: hikers-book-ui-hikers-book
    hostname: hikers-book-ui-hikers-book
    restart: always
    depends_on:
      - hikers-book-api-graphql
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: hikers-book
    ports:
      - 80:80
    volumes:
      - ./config/ui.hikers-book.json:/usr/share/nginx/html/config.json:ro
  hikers-book-api-graphql:
    image: radoslavirha/hikers-book-api-graphql:$VERSION
    container_name: hikers-book-api-graphql
    hostname: hikers-book-api-graphql
    restart: always
    ports:
      - 8083:8083
    volumes:
      - ./config/api.graphql.json:/app/api/graphql/config/production.json:ro