apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-trips-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-trips
  template:
    metadata:
      labels:
        app: api-trips
    spec:
      volumes:
        - name: api-trips-configmap-volume
          configMap:
            name: api-trips-configmap
      initContainers:
        - name: wait-for-redis
          image: goodsmileduck/redis-cli
          imagePullPolicy: IfNotPresent
          args: [ 'sh', '-c', 'until redis-cli  -h redis-srv -p 6379  get hello; do echo "Sleeping a bit"; sleep 1; done; echo "ready!"; ' ]
      containers:
        - name: api-trips
          image: radoslavirha/hikers-book-api-trips
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app/api/trips/config
              name: api-trips-configmap-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-trips-configmap
data:
  production.json: |
    {
      "apis": {
        "hikersBook": {
          "authenticationAPI": "http://authentication-srv:4000"
        }
      },
      "mongodb": {
        "url": "mongodb://mongodb-trips-srv:27017/trips",
        "connectionOptions": {}
      },
      "redis": {
        "default": {
          "host": "redis-srv",
          "port": 6379,
          "username": "",
          "password": ""
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: trips-srv
spec:
  selector:
    app: api-trips
  ports:
    - name: api-trips
      protocol: TCP
      port: 4000
      targetPort: 4000
