name: Pull Request Labeler

on:
  pull_request:
    types: 
      - opened
      - edited

jobs:
  labeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Glob Labeler
        uses: actions/labeler@v4
      - name: Branch Labeler
        uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Conventional Commits Labeler
        uses: bcoe/conventional-release-labels@v1