name: Release please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release please
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release_created }}
      releases: ${{ steps.release.outputs.releases_created }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

  trigger-docker:
    name: Build & Publish ${{ matrix.docker.name }} to Docker Hub
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release
    steps:
      - name: Call Build & Publish to Docker Hub from Tag
        uses: ./workflows/manually-build-docker.yml
        with:
          tag: ${{ needs.release-please.outputs.version }}
