name: Release please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release please
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release_created }}
      releases: ${{ steps.release.outputs.releases_created }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

  api-graphql:
    name: Build & Publish GraphQL API to Docker Hub
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.api.graphql.dockerfile
          push: true
          tags: radoslavirha/hikers-book-api-graphql:${{ needs.release-please.outputs.version }},radoslavirha/hikers-book-api-graphql:latest

  ui-hikers-book:
    name: Build & Publish Hiker's Book UI to Docker Hub
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.ui.hikers-book.dockerfile
          push: true
          tags: radoslavirha/hikers-book-ui-hikers-book:${{ needs.release-please.outputs.version }},radoslavirha/hikers-book-ui-hikers-book:latest