name: Build and Publish to Docker Hub

on:
  release:
    types:
      - released

jobs:
  api-graphql:
    runs-on: ubuntu-latest
    name: Publish GraphQL API to Docker Hub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.api.graphql.dockerfile
          push: true
          tags: radoslavirha/hikers-book-api-graphql:${{ github.event.release.tag_name }},radoslavirha/hikers-book-api-graphql:latest

  ui-hikers-book:
    runs-on: ubuntu-latest
    name: Publish Hiker's Book UI to Docker Hub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.ui.hikers-book.dockerfile
          push: true
          tags: radoslavirha/hikers-book-ui-hikers-book:${{ github.event.release.tag_name }},radoslavirha/hikers-book-ui-hikers-book:latest
